language: node_js

node_js:
  - "v10.6.0"

cache:
  yarn: true
  directories:
    - "node_modules"

script:
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: dist
  target-branch: master
  committer-from-gh: true
  github-token: $GITHUB_TOKEN
  on:
    branch: dev
