language: node_js

node_js:
- v14.6.0

script:
- npm run clean
- npm run lint
- npm run build

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: dist
  target-branch: master
  committer-from-gh: true
  github-token: $GITHUB_TOKEN
  on:
    branch: dev
    condition: $TRAVIS_EVENT_TYPE != cron
